spring:
  datasource:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 300000
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
